# Generated by Django 5.0.3 on 2024-03-18 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='expirystrikeprice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ce', models.TextField()),
                ('pe', models.TextField()),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company_name')),
            ],
        ),
    ]
