# Generated by Django 5.0.3 on 2024-03-26 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_expirystrikeprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_id', models.CharField(default='8F08069815499188382854', max_length=100)),
                ('strategy_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('segments', models.CharField(blank=True, max_length=255, null=True)),
                ('optiontype', models.CharField(blank=True, max_length=255, null=True)),
                ('variety', models.CharField(blank=True, max_length=255, null=True)),
                ('tradingsymbol', models.CharField(blank=True, max_length=255, null=True)),
                ('symboltoken', models.CharField(blank=True, max_length=255, null=True)),
                ('transactiontype', models.CharField(blank=True, max_length=255, null=True)),
                ('exchange', models.CharField(blank=True, max_length=255, null=True)),
                ('ordertype', models.CharField(blank=True, max_length=255, null=True)),
                ('producttype', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('stoploss', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('triggerprice', models.CharField(blank=True, max_length=255, null=True)),
                ('expirydate', models.CharField(blank=True, max_length=255, null=True)),
                ('strikeprice', models.CharField(blank=True, max_length=255, null=True)),
                ('totallot', models.IntegerField(blank=True, null=True)),
                ('trailingstoploss', models.CharField(blank=True, max_length=255, null=True)),
                ('strategy_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.strategy')),
            ],
        ),
    ]
