# Generated by Django 5.0.3 on 2024-03-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_strategy_leg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leg',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='strategy_id',
            field=models.CharField(default='D2D2136748705784211', max_length=100),
        ),
    ]
