# Generated by Django 5.0.3 on 2024-03-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_leg_id_alter_strategy_strategy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leg',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='strategy_id',
            field=models.CharField(default='9CF9051146814679845', max_length=100),
        ),
    ]
