# Generated by Django 5.0.3 on 2024-03-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_signinuser_alter_strategy_strategy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signinuser',
            name='username',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='strategy_id',
            field=models.CharField(default='E131373196554762228391', max_length=100),
        ),
    ]
