# Generated by Django 5.0.3 on 2024-03-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_signinuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signinuser',
            name='user_id',
            field=models.CharField(default='AF44383143346858005933220', max_length=100),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='strategy_id',
            field=models.CharField(default='A70707886396409283043492010', max_length=100),
        ),
    ]
