# Generated by Django 5.0.3 on 2024-04-01 08:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_strategy_user_id_alter_signinuser_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name='signinuser',
            name='user_id',
            field=models.CharField(default='6EF6995848754277301579', max_length=100),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='strategy_id',
            field=models.CharField(default='E3A36368744291187924', max_length=100),
        ),
    ]
