# Generated by Django 5.0.3 on 2024-04-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_strategy_datetime_alter_signinuser_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signinuser',
            name='user_id',
            field=models.CharField(default='5A7572871581846998895804', max_length=100),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='strategy_id',
            field=models.CharField(default='5F9596096541404916947743', max_length=100),
        ),
    ]
