# Generated by Django 5.0.3 on 2024-04-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_signinuser_user_id_alter_strategy_strategy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signinuser',
            name='user_id',
            field=models.CharField(default='0BE0451045491586461968175', max_length=100),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='strategy_id',
            field=models.CharField(default='STA192D9BD', max_length=100, unique=True),
        ),
    ]
