# Generated by Django 5.0.3 on 2024-04-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_signinuser_user_id_alter_strategy_strategy_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategy',
            old_name='status',
            new_name='Status',
        ),
        migrations.AlterField(
            model_name='signinuser',
            name='user_id',
            field=models.CharField(default='EF666765996459922546409', max_length=100),
        ),
    ]
