# Generated by Django 5.0.3 on 2024-04-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_rename_status_strategy_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategy',
            old_name='Status',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='signinuser',
            name='user_id',
            field=models.CharField(default='36F3650140171154711', max_length=100),
        ),
    ]
